-- Moondicine question bank and device-data-compatible schema.
-- Run this in Supabase SQL Editor or with an authenticated Supabase CLI.

create table if not exists public.questions (
    id bigint generated by default as identity primary key,
    exam_source text not null,
    question_number integer not null,
    question_text text not null,
    specialty text not null,
    sub_topic text not null,
    difficulty integer not null default 3 check (difficulty between 1 and 5),
    image_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists questions_exam_number_uq
    on public.questions (exam_source, question_number);
create index if not exists questions_specialty_idx on public.questions (specialty);

create table if not exists public.answer_options (
    id bigint generated by default as identity primary key,
    question_id bigint not null references public.questions(id) on delete cascade,
    option_letter text not null check (option_letter in ('A', 'B', 'C', 'D', 'E')),
    option_text text not null,
    is_correct boolean not null default false,
    unique (question_id, option_letter)
);
create index if not exists answer_options_question_idx on public.answer_options (question_id);

-- These tables mirror the local Room model. User progress remains local in the app;
-- they are available for a future authenticated account-sync feature.
create table if not exists public.user_profile (
    id integer primary key,
    name text not null default '',
    target_specialty text not null default '',
    experience_level text not null default '',
    onboarding_completed boolean not null default false,
    join_date timestamptz not null default now(),
    total_questions_answered integer not null default 0,
    current_streak_days integer not null default 0,
    last_study_date timestamptz,
    total_study_time_minutes integer not null default 0
);

create table if not exists public.user_answers (
    id bigint generated by default as identity primary key,
    question_id bigint not null references public.questions(id) on delete cascade,
    selected_option_id bigint not null references public.answer_options(id) on delete cascade,
    is_correct boolean not null,
    time_spent_seconds integer not null default 0,
    answered_at timestamptz not null default now(),
    is_flagged boolean not null default false
);
create index if not exists user_answers_question_idx on public.user_answers (question_id);

create table if not exists public.question_notes (
    id bigint generated by default as identity primary key,
    question_id bigint not null references public.questions(id) on delete cascade,
    note_text text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.ai_explanations (
    id bigint generated by default as identity primary key,
    question_id bigint not null references public.questions(id) on delete cascade,
    explanation_text text not null,
    correct_reasoning text not null,
    wrong_reasoning jsonb not null default '{}'::jsonb,
    cached_at timestamptz not null default now()
);

create table if not exists public.user_stats (
    id bigint generated by default as identity primary key,
    specialty text not null unique,
    total_answered integer not null default 0,
    total_correct integer not null default 0,
    average_time_seconds real not null default 0,
    last_studied_at timestamptz not null default now(),
    weakest_sub_topics jsonb not null default '[]'::jsonb
);

-- The mobile app only needs anonymous read access to the question bank.
alter table public.questions enable row level security;
alter table public.answer_options enable row level security;
drop policy if exists "Anyone can read published questions" on public.questions;
drop policy if exists "Anyone can read question options" on public.answer_options;
create policy "Anyone can read published questions"
    on public.questions for select to anon, authenticated using (true);
create policy "Anyone can read question options"
    on public.answer_options for select to anon, authenticated using (true);

-- Do not expose user-progress tables to anonymous clients by default.
alter table public.user_profile enable row level security;
alter table public.user_answers enable row level security;
alter table public.question_notes enable row level security;
alter table public.ai_explanations enable row level security;
alter table public.user_stats enable row level security;
